### ISSUE TITLE
Q: Purpose of <Link>?

### ISSUE THREAD

**Issue by dvdplm** [koistya/react-static-boilerplate#48]
What is the idea with the `<Link>` component in the context of a static page generating project? From reading the code I assume its purpose is to intercept clicks and use pushState to manage browsing history, but what is the point of doing that when the final rendered static pages do not use the same mechanism?

`<Link>` as it stands seem to work poorly with named anchors and `mailto:` links. Do we really need it?

**Comment by dsernst** [comment]
I've wondered this as well.

**Comment by cobbweb** [comment]
`Link` looks like a hacky copy from [react-router's `Link`](https://github.com/rackt/react-router/blob/master/modules/Link.js).

> but what is the point of doing that when the final rendered static pages do not use the same mechanism?

The generated static site *does* use it. Once the page is loaded, you can use `Link` to route between different pages and it will render them without a refresh.

I'm not sure what @koistya's motives were with making it static, but I've hacked my own version of it that lets you use it as a component again.

> <Link> as it stands seem to work poorly with named anchors and mailto: links. Do we really need it?

You wouldn't use `Link` in these case because it's not a navigable route within the static route, just use a regular `<a>`.

**Comment by danielstorch** [comment]
Hey, im new too all this and im wondering how i can trigger something (example saving data) before routing to another page. 

<a className="Navigation-sub-link" href="/test" onClick={Link.handleClick}>test</a>

Since the onClick is used for routing, how can i trigger another method when clicking on the <a> element? Is it possible to wrap the element?

Thanks!

**Comment by dsernst** [comment]
Yeah, have you tried a custom onClick function that wraps the Link.handleClick (passing through the arguments), and adds your functionality?

**Comment by cobbweb** [comment]
@danielstorch This is why I modded `Link` so it can be used as a component, then you can simply pass it `href` as well as custom `onClick` event where required. See my [custom `Link`](https://github.com/cobbweb/golittle.red/blob/c730a364e852c82254bd24bb90222ee284d3704a/components/Link/Link.js).

**Comment by koistya** [comment]
I have updated the `Link` component, here:

https://github.com/koistya/react-static-boilerplate/blob/master/components/Link/Link.js

It's intended to be used instead of `<a>` in places where you need to cancel the default behavior of a link (which cases full-page refresh) and just push navigation URL path to HTML5 history. See `main.js`:

```js
history.listen(location =>/* re-render the app */);
```
