### ISSUE TITLE
Dynamic Pages?

### ISSUE THREAD

**Issue by shaekuronen** [koistya/react-static-boilerplate#57]
Has anyone extended this boilerplate to generate pages from a json file, vs from files in the /pages directory?

What I'd like to do is have a /data/pages.json (which would get pulled in dynamically on build from a db, but let's walk before we run ;). Each page is composed of sections, which would be React components. Something like...
```
[
  {
    "name": "01",
    "sections": [
      {
        "template": "one-col",
        "headline": "page 1 section 1 headline",
        "cta": "page 1 section 1 cta"
      },
      {
        "template": "two-col",
        "headline": "page 1 section 2 headline",
        "cta": "page 1 section 2 cta"
      }
    ]
  },
  {
    "name": "02",
    "sections": [
      {
        "template": "two-col",
        "headline": "page 2 section 1 headline",
        "cta": "page 2 section 1 cta"
      },
      {
        "template": "one-col",
        "headline": "page 2 section 2 headline",
        "cta": "page 2 section 2 cta"
      }
    ]
  }
]
```
Looking at getPages in render.js, could extend the files object with any pages in /data/pages.json before iterating through, but maybe there's a better approach?

Any ideas?

**Comment by koistya** [comment]
One way of approaching this problem is by creating a custom loader for Webpack that will pull data from a database. You can take a look at the Markdown example here:

[/routes/about/index.js#L21](https://github.com/koistya/react-static-boilerplate/blob/34525ee8202673062d6c96eb6348ec7f75d0325d/routes/about/index.js#L21)
[/tools/webpack.config.js#L100-L103](https://github.com/koistya/react-static-boilerplate/blob/34525ee8202673062d6c96eb6348ec7f75d0325d/tools/webpack.config.js#L100-L103)
[/tools/webpack.markdown-loader.js](https://github.com/koistya/react-static-boilerplate/blob/34525ee8202673062d6c96eb6348ec7f75d0325d/tools/webpack.markdown-loader.js)

I will close this issue for now, since it was open for a long time. But feel free to reopen!

**Comment by koistya** [comment]
@shaekuronen this has been implemented, the routes are now generated from the `/routes.json`, check it out:

https://github.com/kriasoft/react-static-boilerplate/blob/master/routes.json
https://github.com/kriasoft/react-static-boilerplate/blob/master/utils/routes-loader.js
